name: Update streak stats

on:
  schedule:
    - cron: "0 3 * * *" # Roda todos os dias às 03:00 UTC
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Roda quando esse arquivo for alterado
  workflow_dispatch: # Permite rodar manualmente pela aba Actions

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Baixar arquivos do repositório do perfil
        uses: actions/checkout@v4

      - name: Gerar imagem do GitHub Streak
        uses: denismmartins-web/github-readme-streak-stats@vercel
        with:
          options: user=denismmartins-web&theme=default&locale=pt_BR
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Salvar imagem gerada no repositório
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git pull --rebase origin vercel
          git push origin vercel
